name: Ubuntu-nvcc

on:
  push:
    branches: main
  pull_request:

jobs:
  install-and-test-nvcc:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Check nvcc exists
        run: nvcc --version
