name: Windows-gcc

on:
  push:
    branches: main
  pull_request:

jobs:
  install-and-test-gcc:
    strategy:
      fail-fast: false
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3

    - name: Install gcc-12 using homebrew
      run: brew install gcc@12
    - name: Now test the compiler
      run: gcc-12 --version
