name: macOS-ifort

on:
  push:
    branches: main
  pull_request:

jobs:
  install-and-test-ifort:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install intel C/C++ compiler
        run: |
          curl -O https://registrationcenter-download.intel.com/akdlm/irc_nas/19106/m_fortran-compiler-classic_p_2023.0.0.25379_offline.dmg
          hdiutil attach m_fortran-compiler-classic_p_2023.0.0.25379_offline.dmg
          sudo /Volumes/m_fortran-compiler-classic_p_2023.0.0.25379_offline/bootstrapper.app/Contents/MacOS/bootstrapper --action install -c --eula accept
          hdiutil unmount /Volumes/m_fortran-compiler-classic_p_2023.0.0.25379_offline
      - name: Compile basic Fortran program
        run: ifort -O2 -march=native -fopenmp -Wall -diag-disable=10441 basic_program.f90 -o basic_program
      - name: Run basic Fortran program
        run: ./basic_program
