name: Windows-gcc

on:
  push:
    branches: main
  pull_request:

jobs:
  install-and-test-gcc:
    strategy:
      fail-fast: false
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Install gcc using chocolatey
      run: choco install mingw
    - name: Test C compiler
      run: gcc --version
    - name: Test C++ compiler
      run: g++ --version
    - name: Test Fortran compiler
      run: gfortran --version
