name: Windows-g++

on:
  push:
    branches: main
  pull_request:

jobs:
  test-gplusplus:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2019]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Compile a simple C++ program
      run: g++ -O2 -march=native -fopenmp -Wall basic_program.cc -o basic_program.exe

    - name: Run a simple C++ program
      run: .\basic_program.exe
        

