name: Windows-gcc

on:
  push:
    branches: main
  pull_request:

jobs:
  install-and-test-gcc:
    strategy:
      fail-fast: false
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Install gcc using chocolatey
      run: choco install gcc
    - name: Now test the compiler
      run: gcc --version
