name: Windows-gnu

on:
  push:
    branches: main
  pull_request:

jobs:
  install-and-test-gnu-compilers:
    strategy:
      fail-fast: false
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile a simple C program
      run: gcc -O2 -march=native -fopenmp -Wall basic_program.c -o basic_program_c.exe

    - name: Run a simple C program
      run: .\basic_program_c.exe

    - name: Compile a simple C++ program
      run: g++ -O2 -march=native -fopenmp -Wall basic_program.cc -o basic_program_cpp.exe

    - name: Run a simple C++ program
      run: .\basic_program_cpp.exe
        
    - name: Compile a simple Fortran program
      run: gfortran -O2 -march=native -fopenmp -Wall basic_program.f90 -o basic_program_fortran.exe

    - name: Run a simple Fortran program
      run: .\basic_program_fortran.exe

