name: MacOS-intel

on:
  push:
    branches: main
  pull_request:

jobs:
  install-intel-compilers:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Try installing intel compilers
        run: conda install dpcpp-cpp-rt
      - name: List all conda packages
        run: conda list
